import {Toaster} from "sonner";
import {Header} from "@/components/header";
import {Sidebar} from "@/components/sidebar";
import "@/app/(client)/globals.css"
import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "Next-Backend | Dashboard",
    description: "Generated by create next app",
};


export default function AdminLayout({
                                        children,
                                    }: {
    children: React.ReactNode;
}) {
    return (
        <html>
        <body>

        <div className="flex min-h-screen flex-col">
            <Header/>
            <div className="flex flex-1">
                <Sidebar/>
                <main className="flex-1 p-6">{children}</main>
            </div>
            <Toaster position="bottom-right"/>
        </div>
        </body>
        </html>

    );
}
