import "@/app/(client)/globals.css"
import type {Metadata} from "next";
import Sidebar from "@/ui/sidebar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function DashboardLayout({
                                            children,
                                        }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={"flex"}>
        <Sidebar/>
        {children}
        </body>
        </html>
    );
}
